apiVersion: v1
kind: ReplicaSet
metadata:
  name: webapp
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: webapp 
    spec:
      containers:
      - name: webapp-release-0-5
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5-multi
---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1-multi